### ISSUE TITLE
Proselint cache corrupts itself

### ISSUE THREAD

**Issue by Orbtial** [AtomLinter/linter-proselint#44]
Proselint not linting. CLI shows it though :/

Have tested with multiple file extensions

**Comment by Arcanemagus** [comment]
Was it working before updating?

**Comment by danielbayley** [comment]
Same for me… I keep getting the following error in the console:
~~~
linter-registry.js [sm]:144 [Linter] Error running proselint SyntaxError: Unexpected token C in JSON at position 0
    at JSON.parse (<anonymous>)
    at index.js [sm]:30
    at process._tickCallback (internal/process/next_tick.js:103)
(anonymous) @ linter-registry.js [sm]:144
_tickCallback @ internal/process/next_tick.js:103
Promise.reject (async)
_tickCallback @ internal/process/next_tick.js:103
Promise.reject (async)
_tickCallback @ internal/process/next_tick.js:103
Promise.resolve (async)
_tickCallback @ internal/process/next_tick.js:103
Promise.resolve (async)
step @ /Users/Dan/Library/Application Support/Atom/packages/build/node_modules/sb-exec/lib/index.js:113
(anonymous) @ /Users/Dan/Library/Application Support/Atom/packages/build/node_modules/sb-exec/lib/index.js:113
_tickCallback @ internal/process/next_tick.js:103
~~~

macOS 10.12.5 Sierra
Atom 1.19.0-beta1
linter-proselint 3.2.1
~~~ sh
> brew install proselint
> which proselint
/usr/local/bin/proselint
~~~
I don't think it's a problem with the `PATH`, as I have [_env-from-shell_](https://atom.io/packages/env-from-shell) running.

**Comment by suchow** [comment]
@Arcanemagus Anything I can do on the Proselint side to help with this?

**Comment by Arcanemagus** [comment]
@suchow It looks like this is due to the Proselint cache getting corrupted, the full message is:

```python
Could not open cache file C:\Users\username\.proselint\checks.spelling.misc.check, maybe name collision. Error: Traceback (most recent call last):
  File "c:\program files\python36\lib\site-packages\proselint\tools.py", line 56, in _get_cache
    cache = shelve.open(cachepath, protocol=2)
  File "c:\program files\python36\lib\shelve.py", line 243, in open
    return DbfilenameShelf(filename, flag, protocol, writeback)
  File "c:\program files\python36\lib\shelve.py", line 227, in __init__
    Shelf.__init__(self, dbm.open(filename, flag), protocol, writeback)
  File "c:\program files\python36\lib\dbm\__init__.py", line 94, in open
    return mod.open(file, flag, mode)
  File "c:\program files\python36\lib\dbm\dumb.py", line 324, in open
    return _Database(file, mode, flag=flag)
  File "c:\program files\python36\lib\dbm\dumb.py", line 71, in __init__
    self._update()
  File "c:\program files\python36\lib\dbm\dumb.py", line 106, in _update
    key, pos_and_siz_pair = _ast.literal_eval(line)
  File "c:\program files\python36\lib\ast.py", line 48, in literal_eval
    node_or_string = parse(node_or_string, mode='eval')
  File "c:\program files\python36\lib\ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 0
    
    ^
SyntaxError: unexpected EOF while parsing

Using in-memory shelf for cache file C:\Users\username\.proselint\checks.spelling.misc.check
{"data": {"errors": []}, "status": "success"}
```

Is that enough to track down the problem? I have an archive of the corrupt cache if you need that.

**Comment by Arcanemagus** [comment]
@fcooper8472, @danielbayley, and @Wardlich it looks like if you rename/delete `~/.proselint` this will start working... till it gets corrupted again 😛.

**Comment by Arcanemagus** [comment]
Note that it actually is returning the expected results at the end, but as we are attempting to parse this directly as JSON it is failing.

**Comment by fcooper8472** [comment]
> @fcooper8472, @danielbayley, and @Wardlich it looks like if you rename/delete ~/.proselint this will start working... till it gets corrupted again .

Can confirm that this (at least temporarily) resolves the issue. Thanks!

**Comment by Arcanemagus** [comment]
Closing this, this can only be fixed by `proselint` itself.
