### ISSUE TITLE
Process execution timeout errors?

### ISSUE THREAD

**Issue by gammacray** [AtomLinter/linter-proselint#89]
First, sorry if I use vague and improper terminology — this is my first bug report and I'm about as non-dev as it gets. I've been using Atom for a few weeks with varying success, getting to know it. I've been using linter-proselint for a couple of days. 

Until today it was running fine. Not sure what changed, but I started getting these errors:

```
[Linter] Error running proselint Error: Process execution timed out
    at C:\Users\myusername\.atom\packages\linter-proselint\node_modules\sb-exec\lib\index.js:89:18
(anonymous) @ C:\Users\myusername\.atom\packages\linter\lib\linter-registry.js:154
linter-proselint.svg:1 

Failed to load resource: the server responded with a status of 503 (Service Temporarily Unavailable)
internal/process/warning.js:18 

(node:8680) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
writeOut @ internal/process/warning.js:18
11C:\Users\myusername\.atom\packages\linter\lib\linter-registry.js:154 

[Linter] Error running proselint Error: Process execution timed out
    at C:\Users\myusername\.atom\packages\linter-proselint\node_modules\sb-exec\lib\index.js:89:18
(anonymous) @ C:\Users\myusername\.atom\packages\linter\lib\linter-registry.js:154
```

It happens when I type fast, the fans ramp up and eventually it starts spitting errors. I've seen similar execution timout error bugs mentioned from years past, related to linter, but I haven't found a solution. Is there a line or setting I can extend the timeout delay, or simply ignore the error so it stop spitting out warnings? Proselint is still working as expected, even as it spits out about a dozen warnings. I'm confused.

I want to add that my files are not huge. They're strictly text files and under 1000 words. I'm not parsing a whole book at a time. I hope that information is helpful.

Thanks in advance. And thanks for your work on this awesome package. I love it!

**Comment by gammacray** [comment]
Closing. Sladewin's code fix for timeout issue works. Cheers.
